CC=clang++
CFLAGS=-fsycl -fsycl-targets=nvptx64-nvidia-cuda -std=c++17 -O1 -DUSEFLOAT32
LDFLAGS=-fsycl -fsycl-targets=nvptx64-nvidia-cuda
# CFLAGS=-fsycl -ffp-model=precise -std=c++17 -O1 -DUSEFLOAT32
# LDFLAGS=-fsycl -ffp-model=precise

INCLUDES=-Iincludes

OBJECTS=main.o funcs.dp.o calcs.dp.o affine.dp.o params.dp.o kernel_assembleElems.dp.o

all: main

main: $(OBJECTS)
	$(CC) -o $@ $^ $(LDFLAGS)

%.o: %.cpp
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@

clean:
	rm -f *.o main
