CC=syclcc
CFLAGS=--hipsycl-targets=cuda:sm_80 -std=c++17 -fp-model=precise -O1 -DUSEFLOAT32
# CFLAGS=--hipsycl-targets=omp -std=c++17 -fp-model=precise -O1 -DUSEFLOAT32
LDFLAGS=

INCLUDES=-Iincludes

OBJECTS=main.o funcs.dp.o calcs.dp.o affine.dp.o params.dp.o kernel_assembleElems.dp.o

all: main

main: $(OBJECTS)
	$(CC) -o $@ $^ $(LDFLAGS)

%.o: %.cpp
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@

clean:
	rm -f *.o main
