name: DPC++

on:
  push:
    branches: [ "gh-action-lfs" ]

jobs:
  build-dpcpp:

    runs-on: ubuntu-latest
    container:
      image: intel/oneapi-basekit:latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install git-lfs
      run: curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
    
    - name: Checkout LFS objects
      run: git lfs pull
    
    - name: Compile
      working-directory: ${{github.workspace}}/sycl
      run: make -f Makefile.dpcpp
    
    - name: Run on 48 elements
      working-directory: ${{github.workspace}}/sycl
      run: ./main ${{github.workspace}}/inout/e48_t192 | grep "All values are correct"
  
    - name: Run on 384 elements
      working-directory: ${{github.workspace}}/sycl
      run: ./main ${{github.workspace}}/inout/e384_t1536 | grep "All values are correct"
