name: DPC++

on:
  push:
    branches: [ "gh-actions" ]

jobs:
  build-dpcpp:

    runs-on: ubuntu-latest
    # container:
    #   image: intel/oneapi-basekit:latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Checkout LFS objects
      run: git lfs pull
    
    - name: Setup OneAPI
      run: |
        wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB \
        | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
        sudo apt -y update
    
    - name: Install OneAPI
      run: |
        sudo apt install -y intel-oneapi-common-vars
        sudo apt install -y intel-oneapi-compiler-dpcpp-cpp
    
    - name: Compile
      working-directory: ${{github.workspace}}/sycl
      run: |
        source /opt/intel/oneapi/setvars.sh
        make -f Makefile.dpcpp
    
    - name: Run on 48 elements
      working-directory: ${{github.workspace}}/sycl
      run: |
        source /opt/intel/oneapi/setvars.sh
        ./main ${{github.workspace}}/inout/e48_t192
  
    - name: Run on 384 elements
      working-directory: ${{github.workspace}}/sycl
      run: |
        source /opt/intel/oneapi/setvars.sh
        ./main ${{github.workspace}}/inout/e384_t1536
