name: DPC++

on:
  push:
    branches: [ "gh-actions" ]

jobs:
  build-dpcpp:

    runs-on: ubuntu-latest
    container:
      image: intel/oneapi-basekit:latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Checkout LFS objects
      run: git lfs pull
    
    - name: Make
      working-directory: ${{github.workspace}}/sycl
      run: make -f Makefile.dpcpp
    
    - name: Run on 48 elements
      working-directory: ${{github.workspace}}/sycl
      run: ./main ${{github.workspace}}/inout/e48_t192
  
    - name: Run on 384 elements
      working-directory: ${{github.workspace}}/sycl
      run: ./main ${{github.workspace}}/inout/e384_t1536
