name: on_push

on:
  push:
    branches: [ "gh-actions" ]

jobs:
  build-dpcpp:

    runs-on: ubuntu-latest
    container:
      image: tommelt/fusionalp-intel-build-enviroment:latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and run the SYCL code with dpcpp
      run: cd sycl && make -f Makefile.dpcpp && ./main ../inout/e48_t192
