name: DPC++

on:
  push:
    branches: [ "main" ]

jobs:
  build-dpcpp:

    runs-on: ubuntu-latest
    container:
      image: intel/oneapi-basekit:latest

    steps:   
    - name: Install git-lfs
      run: |
        apt-get -y update
        apt-get -y install git-lfs
    
    - name: Checkout github repo (+ download lfs dependencies)
      uses: actions/checkout@v3
      with:
        repository: ${{ github.repository }}
        ref: main
        lfs: true
    
    - name: Compile
      working-directory: ${{ github.workspace }}/sycl
      run: make -f Makefile.dpcpp
    
    - name: Run on 48 elements
      working-directory: ${{ github.workspace }}/sycl
      run: ./main ../inout/e48_t192 | grep "All values are correct"
    
    - name: Run on 384 elements
      working-directory: ${{ github.workspace }}/sycl
      run: ./main ../inout/e384_t1536 | grep "All values are correct"
      
