name: on_push

on:
  push:
    branches: [ "gh-actions" ]

jobs:
  build-dpcpp:

    runs-on: ubuntu-latest
    container:
      image: intel/oneapi-basekit:latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the SYCL code with dpcpp and run it
      run: cd sycl && make -f Makefile.dpcpp && ./main ../inout/e48_t192
